### ISSUE TITLE
{lawn} has been abandoned and archived on CRAN

### ISSUE THREAD

**Issue by mikemahoney218** [JohnCoene/javascript-for-r#10]
As of 2020-01-08, the {lawn} package used to open chapter 1 has been [archived on CRAN](https://cran.r-project.org/package=lawn) and [archived + marked abandoned on GitHub](https://github.com/ropensci-archive/lawn). It may make sense to use a different package as a motivating example in this section.

https://github.com/JohnCoene/javascript-for-r/blob/bedb98701fc96b4b36511ce76328ed7ad5217542/1-01-intro-introduction.Rmd#L17

**Comment by JohnCoene** [comment]
Oh goodness no! 

Thank you for flagging this, thankfully the book is not printed yet. I'll make that change.

**Comment by mikemahoney218** [comment]
I'm glad I commented then! :)

**Comment by JohnCoene** [comment]
Thanks again, I did change that in the final version of the book.
